# Storkitty 配置文件

[server]
host = "0.0.0.0"
port = 3330

[user]
username = ""
password_hash = ""
email = ""

[jwt]
secret_key = "your-super-secret-jwt-key-change-this-in-production"
expiration_hours = 24

[files]
root_directory = "./uploads"
max_file_size = 100
allowed_extensions = []
blocked_extensions = [".exe", ".bat", ".sh"]

[security]
allow_mkdir = true
allow_delete = true
allow_download = true