/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as SetupRouteImport } from './setup'
import { Route as LoginRouteImport } from './login'
import { Route as SettingsRouteRouteImport } from './settings/route'
import { Route as ListRouteRouteImport } from './list/route'
import { Route as IndexRouteImport } from './index'
import { Route as SettingsUserRouteRouteImport } from './settings/user/route'
import { Route as SettingsUserIndexRouteImport } from './settings/user/index'
import { Route as SettingsUserSecurityRouteImport } from './settings/user/security'
import { Route as SettingsUserProfileRouteImport } from './settings/user/profile'
import { Route as ListSpaceSplatRouteImport } from './list/$space/$'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRouteRoute = ListRouteRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUserRouteRoute = SettingsUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsUserIndexRoute = SettingsUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsUserRouteRoute,
} as any)
const SettingsUserSecurityRoute = SettingsUserSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsUserRouteRoute,
} as any)
const SettingsUserProfileRoute = SettingsUserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsUserRouteRoute,
} as any)
const ListSpaceSplatRoute = ListSpaceSplatRouteImport.update({
  id: '/$space/$',
  path: '/$space/$',
  getParentRoute: () => ListRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list': typeof ListRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings/user': typeof SettingsUserRouteRouteWithChildren
  '/list/$space/$': typeof ListSpaceSplatRoute
  '/settings/user/profile': typeof SettingsUserProfileRoute
  '/settings/user/security': typeof SettingsUserSecurityRoute
  '/settings/user/': typeof SettingsUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list': typeof ListRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/list/$space/$': typeof ListSpaceSplatRoute
  '/settings/user/profile': typeof SettingsUserProfileRoute
  '/settings/user/security': typeof SettingsUserSecurityRoute
  '/settings/user': typeof SettingsUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/list': typeof ListRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/settings/user': typeof SettingsUserRouteRouteWithChildren
  '/list/$space/$': typeof ListSpaceSplatRoute
  '/settings/user/profile': typeof SettingsUserProfileRoute
  '/settings/user/security': typeof SettingsUserSecurityRoute
  '/settings/user/': typeof SettingsUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/list'
    | '/settings'
    | '/login'
    | '/setup'
    | '/settings/user'
    | '/list/$space/$'
    | '/settings/user/profile'
    | '/settings/user/security'
    | '/settings/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/list'
    | '/settings'
    | '/login'
    | '/setup'
    | '/list/$space/$'
    | '/settings/user/profile'
    | '/settings/user/security'
    | '/settings/user'
  id:
    | '__root__'
    | '/'
    | '/list'
    | '/settings'
    | '/login'
    | '/setup'
    | '/settings/user'
    | '/list/$space/$'
    | '/settings/user/profile'
    | '/settings/user/security'
    | '/settings/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListRouteRoute: typeof ListRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/user': {
      id: '/settings/user'
      path: '/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof SettingsUserRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/user/': {
      id: '/settings/user/'
      path: '/'
      fullPath: '/settings/user/'
      preLoaderRoute: typeof SettingsUserIndexRouteImport
      parentRoute: typeof SettingsUserRouteRoute
    }
    '/settings/user/security': {
      id: '/settings/user/security'
      path: '/security'
      fullPath: '/settings/user/security'
      preLoaderRoute: typeof SettingsUserSecurityRouteImport
      parentRoute: typeof SettingsUserRouteRoute
    }
    '/settings/user/profile': {
      id: '/settings/user/profile'
      path: '/profile'
      fullPath: '/settings/user/profile'
      preLoaderRoute: typeof SettingsUserProfileRouteImport
      parentRoute: typeof SettingsUserRouteRoute
    }
    '/list/$space/$': {
      id: '/list/$space/$'
      path: '/$space/$'
      fullPath: '/list/$space/$'
      preLoaderRoute: typeof ListSpaceSplatRouteImport
      parentRoute: typeof ListRouteRoute
    }
  }
}

interface ListRouteRouteChildren {
  ListSpaceSplatRoute: typeof ListSpaceSplatRoute
}

const ListRouteRouteChildren: ListRouteRouteChildren = {
  ListSpaceSplatRoute: ListSpaceSplatRoute,
}

const ListRouteRouteWithChildren = ListRouteRoute._addFileChildren(
  ListRouteRouteChildren,
)

interface SettingsUserRouteRouteChildren {
  SettingsUserProfileRoute: typeof SettingsUserProfileRoute
  SettingsUserSecurityRoute: typeof SettingsUserSecurityRoute
  SettingsUserIndexRoute: typeof SettingsUserIndexRoute
}

const SettingsUserRouteRouteChildren: SettingsUserRouteRouteChildren = {
  SettingsUserProfileRoute: SettingsUserProfileRoute,
  SettingsUserSecurityRoute: SettingsUserSecurityRoute,
  SettingsUserIndexRoute: SettingsUserIndexRoute,
}

const SettingsUserRouteRouteWithChildren =
  SettingsUserRouteRoute._addFileChildren(SettingsUserRouteRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsUserRouteRoute: typeof SettingsUserRouteRouteWithChildren
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsUserRouteRoute: SettingsUserRouteRouteWithChildren,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListRouteRoute: ListRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
