# 用户配置文件
# 密码使用 bcrypt 哈希存储

[user]
username = "admin"
# 密码: admin123 (bcrypt hash)
password_hash = "$2b$12$Y6sTtekn3TUu3fs/rxKzlevMfAx2pRgG2MtMMcJCJWybNRLEC.F9e"
email = "admin@storkitty.com"

[jwt]
# JWT 密钥 (生产环境请使用安全的随机密钥)
secret_key = "your-super-secret-jwt-key-change-this-in-production"
# JWT 过期时间 (24小时)
expiration_hours = 24