/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SetupRouteImport } from "./routes/setup"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SpaceFilesSplatRouteImport } from "./routes/$space/files.$"
import { Route as FilesPreviewDirectoryIdSplatRouteImport } from "./routes/files.preview.$directoryId.$"

const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceFilesSplatRoute = SpaceFilesSplatRouteImport.update({
  id: "/$space/files/$",
  path: "/$space/files/$",
  getParentRoute: () => rootRouteImport,
} as any)
const FilesPreviewDirectoryIdSplatRoute =
  FilesPreviewDirectoryIdSplatRouteImport.update({
    id: "/files/preview/$directoryId/$",
    path: "/files/preview/$directoryId/$",
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/setup": typeof SetupRoute
  "/$space/files/$": typeof SpaceFilesSplatRoute
  "/files/preview/$directoryId/$": typeof FilesPreviewDirectoryIdSplatRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/setup": typeof SetupRoute
  "/$space/files/$": typeof SpaceFilesSplatRoute
  "/files/preview/$directoryId/$": typeof FilesPreviewDirectoryIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/setup": typeof SetupRoute
  "/$space/files/$": typeof SpaceFilesSplatRoute
  "/files/preview/$directoryId/$": typeof FilesPreviewDirectoryIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/setup"
    | "/$space/files/$"
    | "/files/preview/$directoryId/$"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/login"
    | "/setup"
    | "/$space/files/$"
    | "/files/preview/$directoryId/$"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/setup"
    | "/$space/files/$"
    | "/files/preview/$directoryId/$"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  SpaceFilesSplatRoute: typeof SpaceFilesSplatRoute
  FilesPreviewDirectoryIdSplatRoute: typeof FilesPreviewDirectoryIdSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/setup": {
      id: "/setup"
      path: "/setup"
      fullPath: "/setup"
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$space/files/$": {
      id: "/$space/files/$"
      path: "/$space/files/$"
      fullPath: "/$space/files/$"
      preLoaderRoute: typeof SpaceFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/files/preview/$directoryId/$": {
      id: "/files/preview/$directoryId/$"
      path: "/files/preview/$directoryId/$"
      fullPath: "/files/preview/$directoryId/$"
      preLoaderRoute: typeof FilesPreviewDirectoryIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  SpaceFilesSplatRoute: SpaceFilesSplatRoute,
  FilesPreviewDirectoryIdSplatRoute: FilesPreviewDirectoryIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
